version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers-legacy
  working_directory: ~/axe-puppeteer

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-cache-{{ checksum "package.json" }}

      - run:
        name: Install puppeteer dependencies
        command: 'sh .circleci/setup_puppeteer.sh'

      - run: npm install
      - save_cache:
          key: v2-npm-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-cache-{{ checksum "package.json" }}
      - run: npm run coverage
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-cache-{{ checksum "package.json" }}
      - run: npm run lint
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v2-npm-cache-{{ checksum "package.json" }}
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - tests:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - release:
          requires:
            - dependencies
            - tests
            - lint
          filters:
            branches:
              only: master
