version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: ~/axe-puppeteer

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}

      - run:
          name: Install puppeteer dependencies
          command: 'sh .circleci/setup_puppeteer.sh'

      - run: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
      - run: npm run build # smoke test
      - run: npm run coverage
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
      - run: npm run lint
  canary_release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm whoami
      - run: .circleci/next-release.js
      - run: npm publish --tag=next
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm whoami
      - run: npm publish
  github_release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get gopkg.in/aktau/github-release.v0
      - run:
          name: Download and run GitHub release script
          command: |
            curl https://raw.githubusercontent.com/dequelabs/attest-release-scripts/develop/src/node-github-release.sh -s -o ./node-github-release.sh
            chmod +x ./node-github-release.sh
            ./node-github-release.sh

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - tests:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - release:
          requires:
            - dependencies
            - tests
            - lint
          filters:
            branches:
              only: master
      - canary_release:
          requires:
            - dependencies
            - tests
            - lint
          filters:
            branches:
              only: develop
      - github_release:
          requires:
            - release
